In [2]:
import numpy as np

## Creating Arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5, 7, 12]) # List => Array
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(10) # .arange => Same as '.range'.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 10) 

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 10) # Gives 10-no.'s with same consecutive-difference.

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [11]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-Dimensional Arrays

In [12]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n[0, 1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[2]

array([7, 8, 9])

In [ ]:
n[2] = [1, 1, 1] # Access Row.
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
n[:, 1] # Access Column

array([20,  5,  1])

In [ ]:
n[:] # Returns all Columns.

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [24]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Random Generated Arrays

In [32]:
np.random.rand(5, 2) # Random no.'s.
100 * np.random.rand(5, 2)

array([[50.52460901,  6.52865044],
       [42.81223276,  9.65309157],
       [12.71599717, 59.6745309 ],
       [22.60120006, 10.69456843],
       [22.03062071, 34.9826285 ]])

In [ ]:
np.random.seed(2)     # Psuedo Random no.'s, 
np.random.rand(5, 2)  # because O/P is same everytime.

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [37]:
np.random.seed(2)     
np.random.randn(5, 2)  # randn => Gives -ve no.'s

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [38]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element-wise operations

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
a + 1

array([1, 2, 3, 4, 5])

In [41]:
a * 2

array([0, 2, 4, 6, 8])

In [42]:
10 + (a / 2)*3

array([10. , 11.5, 13. , 14.5, 16. ])

In [45]:
b = (10 + (a ** 2)) / 100
b

array([0.1 , 0.11, 0.14, 0.19, 0.26])

In [46]:
a + b

array([0.1 , 1.11, 2.14, 3.19, 4.26])

## Comparison Operations

In [47]:
a

array([0, 1, 2, 3, 4])

In [48]:
a >= 2

array([False, False,  True,  True,  True])

In [50]:
b

array([0.1 , 0.11, 0.14, 0.19, 0.26])

In [51]:
a > b

array([False,  True,  True,  True,  True])

In [52]:
a[a > b] # O/P => All elements index, where (a[i] > b[i]).

array([1, 2, 3, 4])

## Summarizing Operations

In [53]:
a

array([0, 1, 2, 3, 4])

In [56]:
a.min()

np.int64(0)

In [58]:
a.mean()

np.float64(2.0)

In [59]:
a.std() # .std() => Standard deviation.

np.float64(1.4142135623730951)