In [1]:
import numpy as np

# Vector Operations

In [2]:
# Vector => Column Matrix (i.e. 1-Column: Multiple-Rows)
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
v = np.array([1, 0, 0, 2])
u + v

array([3, 4, 5, 8])

In [6]:
u * v # Simple Product.
# Dot Product.
# u * v => (2 + 0 + 0 + 12) = 14.

array([ 2,  0,  0, 12])

## Multiplication

### 1. Vector-Vector multiplication

In [ ]:
v.shape[0] # => Size of Vector.

4

In [18]:
def vector_vector_Multiplication(u, v):
    assert u.shape[0] == v.shape[0] # if (Size of Vector (u == v))

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + (u[i] * v[i])
    
    return result

In [9]:
vector_vector_Multiplication(u, v)

np.float64(14.0)

In [ ]:
u.dot(v) # Inbuilt Vector Dot-Product function

np.int64(14)

### 2. Matrix-Vector multiplication

In [17]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [24]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows) # 1-Dimensional Matrix => Vector.

    for i in range(num_rows):
        result[i] =  vector_vector_Multiplication(U[i], v)

    return result

In [20]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [22]:
U.dot(v) # Inbuilt function.

array([14,  5,  5])

### 3. Matrix-Matrix multiplication

In [23]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [25]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == v.shape[0] # if (No. of (Columns of U == Rows of V).
    
    num_rows = U.shape[0]
    num_columns = V.shape[1]

    result = np.zeros((num_rows, num_columns))

    for i in range(num_columns):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [26]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [27]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity Matrix

In [37]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [40]:
V.dot(I) 
# (V * I = V)  # => (I: Identity Matrix.)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Matrix Inverse

In [43]:
V_square = V[[0, 1, 2]] # Square Matrix from 'V' matrix.
V_square

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [45]:
V_square_Inverse = np.linalg.inv(V_square)
V_square_Inverse # Inverse Matrix of (V_square).

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [46]:
V_square_Inverse.dot(V_square) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])